name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ec2-user-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: manibkt
        AWS_ACCESS_KEY_ID: AKIAQZZPUUQEWUOVQHER
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: 'ap-south-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
